### ISSUE TITLE
There are some problems

### ISSUE THREAD

**Issue by cutexingyun** [ROBlNET13/pvz#4]
There may be a problem with some of your gif format (I don't know if it's a problem with my own computer)
If it's okay, sorry to bother

**Comment by ROBlNET13** [comment]
Which gifs exactly? If you mean the balloonatic, sun or the game over screen it may be because of those being animated pngs (apng but the file extension is still png)

**Comment by cutexingyun** [comment]
I see, sorry to bother.

**Comment by ClaytonTDM** [comment]
Hi, I've fixed this issue. I converted all the APNGs and GIFs to WebP so they should support older browsers now.
